//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppRemax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Maison
    {
        public string refMaison { get; set; }
        public string option { get; set; }
        public string ville { get; set; }
        public Nullable<int> prix { get; set; }
        public Nullable<int> superficie { get; set; }
        public string refAgent { get; set; }
        public string propriete { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
