//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppRemax
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public string refMessage { get; set; }
        public string titre { get; set; }
        public string message1 { get; set; }
        public string date { get; set; }
        public string envoyeur { get; set; }
        public string refAgent { get; set; }
        public string nouveau { get; set; }
    
        public virtual Agent Agent { get; set; }
    }
}
